import client from '../../Sanity/sanity'
import React, { useContext ,useState ,useEffect} from 'react'
import { GlobalData } from '../_app'
import moment from 'moment'
import { useRouter } from 'next/router'
import Head from 'next/head'

function Selected() {


    const router = useRouter()
console.log("selected Arct",router)
const hh = router.query.id
  const {Article} = useContext(GlobalData)

  const [News, setNews] = useState([])

  useEffect(() => {
    client.fetch(`
    *[_type == 'news']{
      _id,
        excerpt,
        categories,
        "imageUrl": mainImage.asset->url,
        
        publishedAt,
       author,
        title,
        slug
      }
    `).then((data)=>{
     console.log(data)
     setNews(data)
    })
   }, [])

   const filteredData = News.filter(item => item._id == hh);

  return (
    <>



    {filteredData.map((g)=>{
      return(
        <>
        <Head>
        <title>{g.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta property={g.title} content={g.title} />
        <meta property="og:image" content={g.imageUrl} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@900&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
        <div className='flex  flex-col h-screen w-full items-center  mt-[100px] px-2'>
  <div className='h-auto md:w-[500px] w-[350px] flex relative flex-col gap-2 px-2 py-4  bg-white shadow-md rounded-md '>
  <img src={g.imageUrl}/>
          <h1 className='Laato px-3 md:px-0 w-full'>{g.title}</h1>
          
          <p className=" text-[10px] lg:text-[14px]  w-full     font-semibold  text-gray-400   ">Updated on {moment(g.publishedAt).format('dddd, MMMM Do YYYY')}</p>

            {g.excerpt}
         
  </div>
        </div>
        </>
      )
    })}
      </>
  )
}

export default Selected